// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zueuvavmzzskdxpkjkei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1ZXV2YXZtenpza2R4cGtqa2VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MTc5NzUsImV4cCI6MjA2NTE5Mzk3NX0.sGYH7WpyIustJbpZ_y8qzNYsBQ-3SXrUK_tWY8B7qQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);